### PR TITLE
validator name for delegations

### PR DESCRIPTION
**Pull request by eesmerdag**

### CODE REVIEW

**Comment by eesmerdag** [comment]
https://www.notion.so/figmentnetworks/validator-name-in-the-information-returns-for-delegations-e16d8a2eb83d4a8d8963a299d99eed84

**Review by pacmessica — APPROVED** [review]
lgtm :)

**Comment by lukanus** [comment]
I'm not sure do we need this, one join in our world is one little puppy killed, is this really necessary @lavabyrd?

**Comment by pacmessica** [comment]
> > I'm not sure do we need this, one join in our world is one little puppy killed, is this really necessary @lavabyrd?
> 
> Ideally, if i can take the overhead off Hubble lookups it'd be great, otherwise I end up doing a `/delegations?holder=...`, then take the validator_id from that and looking at `/validators/:id` to strip the validator name for every delegation attached to a single account/token holder, if its too taxing Indexer side, then we can look at it but it felt like a better option that the manual lookup in Hubble on each load of the account delegations page per token holder

When I saw the join, I thought of you @lukanus  :P was wondering if you'd be critical

Is it really that taxing? Seems like it's a lot nicer than the work around we're forcing hubble to do without the join

**Comment by eesmerdag** [comment]
> > > I'm not sure do we need this, one join in our world is one little puppy killed, is this really necessary @lavabyrd?
> > 
> > 
> > Ideally, if i can take the overhead off Hubble lookups it'd be great, otherwise I end up doing a `/delegations?holder=...`, then take the validator_id from that and looking at `/validators/:id` to strip the validator name for every delegation attached to a single account/token holder, if its too taxing Indexer side, then we can look at it but it felt like a better option that the manual lookup in Hubble on each load of the account delegations page per token holder
> 
> When I saw the join, I thought of you @lukanus :P was wondering if you'd be critical
> 
> Is it really that taxing? Seems like it's a lot nicer than the work around we're forcing hubble to do without the join

i can actually do this: instead of joining on db level, i can call two functions: getDelegations and getValidator By Id and merge them with go. then i think this is not a big problem? what do you think sir? @lukanus

**Comment by lukanus** [comment]
@eesmerdag Nah just merge it and we'll be fine, I can take this puppy on me. 
Just make sure indexes are used for this query.

**Review by lukanus — APPROVED** [review]

**Pull request merged**
